DROP TABLE IF EXISTS _tagtypes;

DROP TABLE IF EXISTS _texts;

DROP TABLE IF EXISTS _tags;

DROP TABLE IF EXISTS tracks;

DROP TABLE IF EXISTS _taggeds;

DROP TABLE IF EXISTS tags;
-- DROP VIEW IF EXISTS tags;
